spring:
  application:
    name: quit-journey-backend
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/quitjourney
    username: quitjourney_user
    password: quitjourney_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  cache:
    type: redis
    redis:
      time-to-live: 600000
  
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.quitjourney: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# JWT Configuration
jwt:
  secret: "quitjourney-secret-key-change-in-production-environment-2024"
  expiration: 900000  # 15 minutes in milliseconds
  refresh-expiration: 2592000000  # 30 days in milliseconds

# API Documentation
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
    displayOperationId: true
    showExtensions: true
    showCommonExtensions: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    docExpansion: none
    filter: true
    tryItOutEnabled: true
  group-configs:
    - group: 'auth'
      displayName: '认证模块'
      pathsToMatch: '/auth/**'
    - group: 'users'
      displayName: '用户管理'
      pathsToMatch: '/users/**'
    - group: 'checkins'
      displayName: '每日打卡'
      pathsToMatch: '/checkins/**'
    - group: 'achievements'
      displayName: '成就系统'
      pathsToMatch: '/achievements/**'
    - group: 'sync'
      displayName: '数据同步'
      pathsToMatch: '/sync/**'
