spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: false  # 禁用Flyway，使用JPA自动创建表
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    # 如果Redis也没有，可以禁用缓存
  
  cache:
    type: simple  # 使用简单的内存缓存而不是Redis

logging:
  level:
    com.quitjourney: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# JWT配置
jwt:
  secret: "test-secret-key-for-development-only"
  expiration: 3600000  # 1 hour
  refresh-expiration: 86400000  # 1 day
