-- 焕新之旅 - 戒烟辅助应用初始成就数据
-- 版本: V2
-- 创建时间: 2025-01-27
-- 描述: 插入系统预定义的成就数据

-- 插入基础成就数据
INSERT INTO achievements (key, name_i18n, description_i18n, icon_name, category, unlock_condition, points, is_active) VALUES
-- 时间类成就
('first_day', 
 '{"zh-CN": "第一天", "en": "First Day"}',
 '{"zh-CN": "成功戒烟第一天", "en": "Successfully quit smoking for the first day"}',
 'calendar_check',
 'time_based',
 '{"type": "consecutive_days", "days": 1}',
 10,
 true),

('one_week',
 '{"zh-CN": "一周成就", "en": "One Week"}',
 '{"zh-CN": "连续戒烟一周", "en": "Quit smoking for one week"}',
 'trophy',
 'time_based',
 '{"type": "consecutive_days", "days": 7}',
 50,
 true),

('half_month',
 '{"zh-CN": "半月成就", "en": "Half Month"}',
 '{"zh-CN": "连续戒烟半个月", "en": "Quit smoking for half a month"}',
 'medal',
 'time_based',
 '{"type": "consecutive_days", "days": 15}',
 100,
 true),

('one_month',
 '{"zh-CN": "一月成就", "en": "One Month"}',
 '{"zh-CN": "连续戒烟一个月", "en": "Quit smoking for one month"}',
 'star',
 'time_based',
 '{"type": "consecutive_days", "days": 30}',
 200,
 true),

('three_months',
 '{"zh-CN": "三月成就", "en": "Three Months"}',
 '{"zh-CN": "连续戒烟三个月", "en": "Quit smoking for three months"}',
 'crown',
 'time_based',
 '{"type": "consecutive_days", "days": 90}',
 500,
 true),

('half_year',
 '{"zh-CN": "半年成就", "en": "Half Year"}',
 '{"zh-CN": "连续戒烟半年", "en": "Quit smoking for half a year"}',
 'diamond',
 'time_based',
 '{"type": "consecutive_days", "days": 180}',
 1000,
 true),

('one_year',
 '{"zh-CN": "一年成就", "en": "One Year"}',
 '{"zh-CN": "连续戒烟一年", "en": "Quit smoking for one year"}',
 'champion',
 'time_based',
 '{"type": "consecutive_days", "days": 365}',
 2000,
 true),

-- 打卡类成就
('check_in_streak_7',
 '{"zh-CN": "打卡达人", "en": "Check-in Master"}',
 '{"zh-CN": "连续打卡7天", "en": "Check in for 7 consecutive days"}',
 'check_circle',
 'checkin_based',
 '{"type": "consecutive_checkins", "days": 7}',
 30,
 true),

('check_in_streak_30',
 '{"zh-CN": "打卡专家", "en": "Check-in Expert"}',
 '{"zh-CN": "连续打卡30天", "en": "Check in for 30 consecutive days"}',
 'verified',
 'checkin_based',
 '{"type": "consecutive_checkins", "days": 30}',
 150,
 true),

('total_checkins_100',
 '{"zh-CN": "百日打卡", "en": "100 Check-ins"}',
 '{"zh-CN": "累计打卡100天", "en": "Total 100 check-ins"}',
 'calendar_today',
 'checkin_based',
 '{"type": "total_checkins", "count": 100}',
 300,
 true),

-- 健康类成就
('money_saved_100',
 '{"zh-CN": "省钱小能手", "en": "Money Saver"}',
 '{"zh-CN": "累计节省100元", "en": "Save 100 yuan in total"}',
 'savings',
 'health_based',
 '{"type": "money_saved", "amount": 100}',
 50,
 true),

('money_saved_1000',
 '{"zh-CN": "理财达人", "en": "Financial Expert"}',
 '{"zh-CN": "累计节省1000元", "en": "Save 1000 yuan in total"}',
 'account_balance',
 'health_based',
 '{"type": "money_saved", "amount": 1000}',
 200,
 true),

('cigarettes_avoided_100',
 '{"zh-CN": "健康卫士", "en": "Health Guardian"}',
 '{"zh-CN": "累计避免吸烟100支", "en": "Avoid smoking 100 cigarettes in total"}',
 'health_and_safety',
 'health_based',
 '{"type": "cigarettes_avoided", "count": 100}',
 100,
 true),

('cigarettes_avoided_1000',
 '{"zh-CN": "生命守护者", "en": "Life Guardian"}',
 '{"zh-CN": "累计避免吸烟1000支", "en": "Avoid smoking 1000 cigarettes in total"}',
 'favorite',
 'health_based',
 '{"type": "cigarettes_avoided", "count": 1000}',
 500,
 true),

-- 特殊成就
('first_login',
 '{"zh-CN": "新手上路", "en": "Getting Started"}',
 '{"zh-CN": "首次登录应用", "en": "First time login to the app"}',
 'login',
 'special',
 '{"type": "first_login"}',
 5,
 true),

('profile_complete',
 '{"zh-CN": "资料完善", "en": "Profile Complete"}',
 '{"zh-CN": "完善个人资料", "en": "Complete personal profile"}',
 'person',
 'special',
 '{"type": "profile_complete"}',
 20,
 true),

('comeback_after_relapse',
 '{"zh-CN": "重新开始", "en": "Fresh Start"}',
 '{"zh-CN": "复吸后重新开始戒烟", "en": "Start quitting again after relapse"}',
 'refresh',
 'special',
 '{"type": "comeback_after_relapse"}',
 30,
 true);
