spring:
  datasource:
    url: jdbc:postgresql://db:5432/quitjourney
    username: quitjourney_user
    password: quitjourney_pass
  
  redis:
    host: redis
    port: 6379
    password: redis_password

logging:
  level:
    com.quitjourney: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
