spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quitjourney_dev
    username: quitjourney_user
    password: quitjourney_pass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.quitjourney: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 开发环境使用较短的JWT过期时间便于测试
jwt:
  secret: "dev-secret-key-not-for-production"
  expiration: 3600000  # 1 hour
  refresh-expiration: 86400000  # 1 day
