spring:
  datasource:
    url: jdbc:h2:mem:quitjourney_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  # 禁用Redis缓存用于开发环境
  cache:
    type: none

  # 禁用Flyway，使用JPA自动建表
  flyway:
    enabled: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.quitjourney: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.boot.autoconfigure: INFO

# 开发环境使用较短的JWT过期时间便于测试
jwt:
  secret: "dev-secret-key-not-for-production"
  expiration: 3600000  # 1 hour
  refresh-expiration: 86400000  # 1 day
